.\"  $NiH: img2eps.mdoc,v 1.19 2005/07/19 09:54:52 dillo Exp $
.\"
.\"  img2eps.mdoc -- man page for img2eps(1)
.\"  Copyright (C) 2002, 2005 Dieter Baron and Thomas Klausner
.\"
.\"  This file is part of img2eps, an image to EPS file converter.
.\"  The authors can be contacted at <dillo@giga.or.at> and
.\"  <tk@giga.or.at> respectively
.\"
.\"  Redistribution and use in source and binary forms, with or without
.\"  modification, are permitted provided that the following conditions
.\"  are met:
.\"  1. Redistributions of source code must retain the above copyright
.\"     notice, this list of conditions and the following disclaimer.
.\"  2. Redistributions in binary form must reproduce the above copyright
.\"     notice, this list of conditions and the following disclaimer in
.\"     the documentation and/or other materials provided with the
.\"     distribution.
.\"  3. The name of the author may not be used to endorse or promote
.\"     products derived from this software without specific prior
.\"     written permission.
.\" 
.\"  THIS SOFTWARE IS PROVIDED BY DIETER BARON ``AS IS'' AND ANY EXPRESS
.\"  OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
.\"  WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\"  ARE DISCLAIMED.  IN NO EVENT SHALL DIETER BARON BE LIABLE FOR ANY
.\"  DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\"  DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
.\"  GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
.\"  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER
.\"  IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
.\"  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
.\"  IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd July 19, 2005
.Dt IMG2EPS 1
.Os
.Sh NAME
.Nm img2eps
.Nd package raster images into EPS file
.Sh SYNOPSIS
.Nm ""
.Op Fl 123
.Op Fl a | Fl -ascii Ar ENC
.Op Fl -bottom-margin Ar M
.Op Fl C | Fl -compress Ar C
.Op Fl c | Fl -stdout
.Op Fl G | Fl -gravity Ar G
.Op Fl g | -gray | -grey
.Op Fl h | Fl -help
.Op Fl -height Ar H
.Op Fl -ignore-order
.Op Fl -left-margin Ar M
.Op Fl -level
.Op Fl m | Fl -margin Ar M
.Op Fl n | Fl -dry-run
.Op Fl O | Fl -orientation Ar O
.Op Fl o | Fl -output Ar FILE
.Op Fl P | Fl -paper Ar P
.Op Fl r | Fl -resolution Ar R
.Op Fl R | Fl -recompress
.Op Fl -right-margin Ar M
.Op Fl s | Fl -size Ar S
.Op Fl -top-margin Ar M
.Op Fl v | Fl -verbose
.Op Fl V | Fl -version
.Op Fl -width Ar W
.Ar file ...
.Sh DESCRIPTION
.Nm
packages each
.Ar file
into an EPS (Embedded PostScript) file, using whatever PostScript
features are advantageous.
The default name for each output file is the name of the input file
with its extension changed to
.Em \&.eps .
Supported image file formats are:
.Bl -bullet -offset indent -compact
.It
GIF
.It
JPEG
.It
PNG
.It
TIFF
.It
XPM
.El
.Pp
If possible, the compressed image data is copied directly to the EPS file.
.Sh The Options
.Bl -tag -width XXXXXXXXXXXXXXXXXX -offset indent -compact
.It Fl 1
Use only features present in PostScript language level 1.
.It Fl 2
Use only features present in PostScript language level 2.
.It Fl 3
Explicitly allow the use of PostScript language level 3 features.
.It Fl a Ar ENC
.It Fl -ascii Ar ENC
Use
.Ar ENC
ASCII encoding for binary data.
Supported encodings are:
.Bl -bullet -offset indent -compact
.It
ASCII85
.It
ASCIIHEX
.El
.It Fl -bottom-margin Ar M
Set bottom margin to
.Ar M .
.It Fl C Ar C
.It Fl -compress Ar C
Use compression method
.Ar C
for image data.
Supported compression methods are:
.Bl -bullet -offset indent -compact
.It
DCT (jpeg)
.It
Flate (zlib)
.It
LZW
.It
RunLength (PackBits)
.El
.It Fl c
.It Fl -stdout
Write EPSF to standard output.
If this option is used, only one input file may be specified.
.It Fl G Ar G
.It Fl -gravity Ar G
Specify the placement of image within the printable area of the page.
The gravity can be either a pair of numbers (see below) in the range
of 0 to 1 inclusive, which specify how much of the free space is
placed to the left / above the image, or one of the following
pre-defined settings:
.Bl -bullet -offset indent -compact
.It
top-left
.It
top
.It
top-right
.It
left
.It
center
.It
right
.It
bottom-left
.It
bottom
.It
bottom-right
.El
.It Fl g
.It Fl -gray
Convert image to grayscale.
.It Fl -height Ar H
Specify the height of the image to be
.Ar H ,
which should be a dimen (see below).
If the width is not specified also, it will be computed to keep the
aspect ratio of the original image.
.It Fl h
.It Fl -help
Display a short help message.
.It Fl -ignore-order
Ignore pixel order information from image and assume row major
left to right, top to bottom.
.It Fl -left-margin Ar M
Set left margin to
.Ar M ,
which should be a dimen (see below).
.It Fl -level Ar L
Use only features present in PostScript language level
.Ar L .
Alternatively, you can also use the
.Fl 1 ,
.Fl 2 ,
and
.Fl 3
options.
.It Fl m Ar M
.It Fl -margin Ar M
Set all margins to
.Ar M ,
which should be a dimen (see below).
.It Fl n
.It Fl -dry-run
Don't create EPSF, only print information about what would have been done.
.It Fl O Ar O
.It Fl -orientation Ar O
Set orientation (rotation) of image:
.Bl -tag -width XXXXXXXXXXXXX -offset indent -compact
.It portrait
Don't rotate image.
.It landscape
Rotate image 90 degrees counter-clockwise.
.It upside-down
Rotate image 180 degrees.
.It seascape
Rotate image 90 degrees clockwise.
.It auto
Use portrait or landscape, whichever fits the image better.
.El
.It Fl o Ar FILE
.It Fl -output Ar FILE
Write EPSF to output file
.Ar FILE .
If this option is used, only one input file may be specified.
.It Fl P Ar P
.It Fl -paper Ar P
Set paper size to
.Ar P .
The paper size can be specified either as a pair of dimens (see
below), or by using one of the following pre-defined sizes:
.Bl -bullet -offset indent -compact
.It
10x14
.It
A3, A4, A5
.It
B4, B5
.It
executive
.It
folio
.It
ledger
.It
legal
.It
letter
.It
quarto
.It
statement
.It
tabloid
.El
.It Fl r Ar R
.It Fl -resolution Ar R
Specify the resolution to print the image at, in dpi (dots per inch).
.Ar R
can be a number to specify equal horizontal and vertical resolution
or a pair of numbers (see below) to specify horizontal and vertical
resolutions separately.
.It Fl R
.It Fl -recompress
Force recompression of image data, even if a direct copy would be
possible.  This might be necessary since PostScript imposes stricter
image data constraints than other image manipulation software.
.It Fl -right-margin Ar M
Set right margin to
.Ar M ,
which should be a dimen (see below).
.It Fl S Ar S
.It Fl -size Ar S
Specify the size of the printed image.
.Ar S
should be a pair of dimens (see below).
.It Fl -top-margin Ar M
Set top margin to
.Ar M ,
which should be a dimen (see below).
.It Fl V
.It Fl -version
Display version number.
.It Fl -width Ar W
Specify the width of the image to be
.Ar W ,
which should be a dimen (see below).
If the height is not specified also, it will be computed to keep the
aspect ratio of the original image.
.El
.Ss Dimens and Pairs
A dimen is a number optionally followed by a unit.
Supported units are:
.Bl -bullet -offset indent -compact
.It
cm
.It
in
.It
mm
.It
pt (PostScript point, 1/72in)
.El
If no unit is specified, pt is assumed.
.Pp
A pair of numbers should be separated by any one of
.Sq x ,
.Sq * ,
or
.Sq \&, .
.Pp
A pair of dimens is a pair of numbers optionally followed by a unit,
which applies to both numbers of the pair.
.Ss Language Levels
There are three major versions of PostScript, called Language Levels:
.Pp
Language Level 1 only supports ASCIIHEX encoded, uncompressed images
and does not support indexed (paletted) images.
.Pp
Language Level 2 adds support for ASCII85 encoding and various
compression schemes, 12 bit samples, and indexed images.
Most PostScript printers support Language Level 2.
.Pp
Language Level 3 adds support for Flate (zlib) compression, a
patent-free lossless compression scheme.
Ghostscript supports Language Level 3, as do most PostScript colour
printers.
.Ss Default Parameters
The default value for any parameter not specified via command line
options is derived from the image:
.Pp
The color space type is taken from the image.
However, for language level 1, indexed images are converted to their
base color space.
.Pp
An unsupported depth is converted to the next higher supported depth,
if it exists, or the highest supported depth (8 for language level 1,
12 for language level 2 or 3).
.Pp
If direct copy of the compressed image data is supported, the
compression method of the image is used.
If the image is compressed with DCT (jpeg), DCT compression is used
even if recompression is necessary.
Otherwise, the best lossless compression method available is used,
which is Flate for language level 3 and LZW for language level 2.
Language level 1 disallows compression altogether.
.Pp
ASCII85 encoding is used for language level 2 or 3, ASCIIHEX for
language level 1.
.Pp
If no language level is specified, the lowest level that supports the
color space type, depth, and, for direct copy or DCT encoding, the
compression method used.
.Sh EXIT STATUS
The
.Nm
utility exits 0 on success, and \*[Gt]0 if an error occurs.
.Sh SEE ALSO
.Xr gs 1
.Rs
.%A Adobe Systems Incorporated
.%B PostScript Language Reference, 3rd edition
.%D 1999
.Re
.Sh AUTHORS
.An -nosplit
.Nm
was written by
.An Dieter Baron Aq dillo@giga.or.at .
.Pp
The manual page was written with the help of
.An Thomas Klausner Aq tk@giga.or.at .
.Pp
The LZW compression routines and various library function replacements
(for portability) were taken from the NetBSD Project.
.Sh BUGS
Since PostScript's JPEG decoder is stricter than most software
implementations, directly copying JPEG compressed data causes
PostScript errors for some images.  This is not detected by
.Nm .
Use
.Fl R
.Pq Fl -recompress
for such images.
.Pp
Emulation of the colorimage operator is provided only for 8bit RGB
images.
(The presence of the operator is assumed for other color formats.)
.Pp
Predictor functions (for LZW or Flate compression) are not supported.
.Pp
TIFF images that include more than one extra sample per pixel, or use
separated planar or tiled layout, are not supported.
Direct copy of LZW compressed TIFF images using the old (bit-swapped)
format is not supported and may result in broken EPS files.
.Pp
Multi-page GIF images are not supported.
