.\" This man page written by Thomas Klausner <tk@giga.or.at>.
.Dd October 10, 2002
.Dt IMG2EPS 1
.Os
.Sh NAME
.Nm img2eps
.Nd insert compressed graphics data into EPS files
.Sh SYNOPSIS
.Nm ""
.Op Fl 123cghV
.Op Fl a | Fl -ascii Ar ENC
.Op Fl C | Fl -compress Ar C
.Op Fl -help
.Op Fl -level
.Op Fl m | Fl -margin Ar M
.Op Fl o | Fl -output Ar FILE
.Op Fl P | Fl -paper Ar P
.Op Fl -version
.Sh DESCRIPTION
.Nm
inserts compressed graphics data into EPS files without converting it.
Supported data formats are:
.Bl -bullet -offset indent -compact
.It
GIF
.It
JPEG
.It
PNG (level 3 only)
.It
TIFF
.El
.Pp
The options are:
.Bl -tag -width XXXXXXXXXXXXX -offset indent -compact
.It Fl 1
Use PostScript language level 1.
.It Fl 2
Use PostScript language level 2.
.It Fl 3
Use PostScript language level 3.
.It Fl a Ar ENC
.It Fl -ascii Ar ENC
Use
.Ar ENC
ASCII encoding for binary data.
.It Fl C Ar C
.It Fl -compress Ar C
Use compression method
.Ar C
for image data.
Supported compression methods are
.Em XXX unknown.
.It Fl c
.It Fl -stdout
Write EPSF to stdout (default).
.It Fl g
.It Fl -gray
Force image to grayscale.
.It Fl h
.It Fl -help
Display a short help message.
.It Fl -level Ar L
Use PostScript language level
.Ar L .
Alternatively, you can also use the
.Fl 1 ,
.Fl 2 ,
and
.Fl 3
options.
.It Fl m Ar M
.It Fl -margin Ar M
Set all margins to
.Ar M
.Em XXX units?
.It Fl o Ar FILE
.It Fl -output Ar FILE
Write EPSF to output file
.Ar FILE .
.It Fl P Ar P
.It Fl -paper Ar P
Set paper size to
.Ar P .
Supported sizes are
.Em XXX unknown .
.It Fl V
.It Fl -version
Display version number.
.El
.Sh SEE ALSO
.Xr gs 1
.Sh AUTHORS
.An Dieter Baron Aq dillo@giga.or.at
